In [1]:
from arguseyes.templates.classification import BinaryClassificationPipeline

In [2]:
pipeline = BinaryClassificationPipeline.from_py_file('argos/example_pipelines/income_classifier.py')

2021-07-13 18:42:35.049333: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

Model accuracy on held-out data 0.8172021684516726

In [3]:
import json

for train_source_metadata, train_source in pipeline.train_sources:
    print(json.dumps(train_source_metadata, indent=2))

{
  "name": "adult.data",
  "num_records": 32561,
  "columns": [
    {
      "name": "age",
      "dtype": "int64",
      "completeness": 1.0,
      "num_distinct": 73
    },
    {
      "name": "workclass",
      "dtype": "object",
      "completeness": 0.943613525383127,
      "num_distinct": 9
    },
    {
      "name": "fnlwgt",
      "dtype": "int64",
      "completeness": 1.0,
      "num_distinct": 21648
    },
    {
      "name": "education",
      "dtype": "object",
      "completeness": 1.0,
      "num_distinct": 16
    },
    {
      "name": "education-num",
      "dtype": "int64",
      "completeness": 1.0,
      "num_distinct": 16
    },
    {
      "name": "marital-status",
      "dtype": "object",
      "completeness": 1.0,
      "num_distinct": 7
    },
    {
      "name": "occupation",
      "dtype": "object",
      "completeness": 0.9433985442707533,
      "num_distinct": 15
    },
    {
      "name": "relationship",
      "dtype": "object",
      "completeness": 1.0,
      "num_distinct": 6
    },
    {
      "name": "race",
      "dtype": "object",
      "completeness": 1.0,
      "num_distinct": 5
    },
    {
      "name": "sex",
      "dtype": "object",
      "completeness": 1.0,
      "num_distinct": 2
    },
    {
      "name": "capital-gain",
      "dtype": "int64",
      "completeness": 1.0,
      "num_distinct": 119
    },
    {
      "name": "capital-loss",
      "dtype": "int64",
      "completeness": 1.0,
      "num_distinct": 92
    },
    {
      "name": "hours-per-week",
      "dtype": "int64",
      "completeness": 1.0,
      "num_distinct": 94
    },
    {
      "name": "native-country",
      "dtype": "object",
      "completeness": 0.9820951444980192,
      "num_distinct": 42
    },
    {
      "name": "income-per-year",
      "dtype": "object",
      "completeness": 1.0,
      "num_distinct": 2
    }
  ]
}

In [4]:
from arguseyes.issues import train_test_overlap, label_shift, unnormalised_features, covariate_shift

train_test_overlap.detect(pipeline)
label_shift.detect(pipeline)
unnormalised_features.detect(pipeline)
covariate_shift.detect(pipeline)

False

In [6]:
from argos.refinements import record_lineage

source_datasets_with_usage = record_lineage.refine(pipeline)

In [7]:
input_df = source_datasets_with_usage[0]

unused = input_df[input_df['__argos__is_used'] == False]
unused

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income-per-year,__argos__is_used
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,False
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K,False
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K,False
33,30,Federal-gov,59951,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K,False
34,22,State-gov,311512,Some-college,10,Married-civ-spouse,Other-service,Husband,Black,Male,0,0,15,United-States,<=50K,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32473,41,Federal-gov,160467,Masters,14,Divorced,Prof-specialty,Unmarried,White,Female,1506,0,40,United-States,<=50K,False
32479,64,State-gov,222966,7th-8th,4,Married-civ-spouse,Other-service,Wife,Black,Female,0,0,40,United-States,<=50K,False
32515,66,Federal-gov,47358,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,3471,0,40,United-States,<=50K,False
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K,False
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K,False

In [8]:
unused.workclass.unique()

array(['State-gov', 'Federal-gov'], dtype=object)